name: shiny.ef.aps.dashboard deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Verificando secrets
      - name: Check VPS_HOST secret
        run: |
          echo "VPS_HOST: $VPS_HOST"
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
      # Usar as actions via SSH para se conectar na VPS e rodar o script
      - name: Deploy VPS
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: root
          REMOTE_PORT: 22
          SOURCE: "./"                       # what folder to rsync from
          TARGET: "/srv/shiny-server/shiny.ef.aps.dashboard/"  # remote folder
          ARGS: "-rlgoDzvc --delete"
          
          # Run your commands AFTER code is synced
          SCRIPT_AFTER: |
            echo "Stopping old R process..."
            pid=$(ps aux | grep "Rscript.R" | awk '{print $2}')
            if [ -n "$pid" ]; then
              echo "Killing process with PID: $pid"
              kill -9 $pid
            else
              echo "No matching process found."
            fi
            
            echo "Pulling latest from Git..."
            cd /srv/shiny-server/shiny.ef.aps.dashboard
            git pull origin main
            
            # Optionally install/refresh R packages
            # Rscript -e "install.packages('remotes'); remotes::install_deps()"

            echo "Starting new R script..."
            Rscript app.R
